### ISSUE TITLE
chunk won't render if LeavesBlock extends Transparent block

### ISSUE THREAD

**Issue by DefinitlyEvil** [CloudLandGame/CloudLand-UnityClient#1]
if let LeavesBlock extends TransparentBlock(so you can see thru leaves and see logs), it will break the renderer and (almost) only chunks have water can be rendered. Why?? Could u look into this @mastercoms ?? 
![screenshot](https://cloud.githubusercontent.com/assets/8604063/25740376/de03029e-31b8-11e7-8275-f366ecad812d.jpg)

**Comment by mastercoms** [comment]
I'll see if I have time this weekend.

**Comment by DefinitlyEvil** [comment]
thx, make sure u commit as soon as you made change to the SCENE since it's binary not text file and git can't solve the conflicts.

**Comment by DefinitlyEvil** [comment]
@mastercoms boops, how's it going? ;)

**Comment by mastercoms** [comment]
I have time to work on it today.

**Comment by mastercoms** [comment]
@DefinitlyEvil Done. I tested it and leaves were transparent without any issues that I could see.

**Comment by DefinitlyEvil** [comment]
@mastercoms awesome!! you're epic!!

**Comment by DefinitlyEvil** [comment]
@mastercoms i just tested this, I wanted TrasparentBlock to behave like glass did in Minecraft, which means nearby blocks with same ID are merged(no faces drawn).

**Comment by DefinitlyEvil** [comment]
I just have the transparency issue accidently solved xD

**Comment by DefinitlyEvil** [comment]
![n28 os9rz94_eiz8 z 0](https://cloud.githubusercontent.com/assets/8604063/26031004/8c14bc08-3897-11e7-9d55-818807d30b4e.png)
I meant to be like this, now the issue is removing water colliders tho I already set `HasFaceCollider()` returns false.
